### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by emilabraham** [HardTacos/riot-games-api-nodejs#3]
It seems to have installed correctly in my project. I see it my node_modules folder. I also see it in my package.json. But when I require the module and attempt to run it, I get a Module not found error. My project can be found on my github: https://github.com/emilabraham/apchange

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'riot-games-api-nodejs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/honestemu/Documents/apchange/apicalls.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by tskaufma** [comment]
I've found in the latest build the package.json says the main is "app.js" when there is no such file. I copied lib\riot-games-api-nodejs.js to app.js and it seems to work.

Hope that helps.

**Comment by emilabraham** [comment]
That did it for me. I'm gonna make a pull request. However, I also found that pointing the main to "./lib/riot-games-api-nodejs.js" also works. Which do you think would better follow the standards, @tskaufma? Your change or the change I tried?

**Comment by tskaufma** [comment]
I think your change would be better as a PR since it doesn't duplicate the code file. I don't know about best practices.

**Comment by emilabraham** [comment]
Pull request merged. That should solve the issue.

**Comment by byWulf** [comment]
@emilabraham Hey :) When will this change be in a stable release for install via npm?

**Comment by emilabraham** [comment]
Paging @HardTacos as he is the publisher of the official npm module.

**Comment by Dowdow** [comment]
Hello ! This change is not on the stable release. Is this repository still maintained ?

**Comment by amcd1443** [comment]
bump still not merged into stable

**Comment by HardTacos** [comment]
changes have been published to npm.
